# generated by fastapi-codegen:
#   filename:  spec.yaml
#   timestamp: 2025-09-18T07:03:56+00:00

from __future__ import annotations

from typing import List, Optional, Union
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded

from fastapi import FastAPI, Depends, Header, HTTPException, Request
from pydantic import conint
from typing import Union, List, Optional
from .services.auth_service import auth_service, refresh_tokens, logout_user_tokens
from .services.SAN_test_service import SANTestService
from .firebase_app import RealtimeDB, verify_firebase_token, create_firebase_custom_token
from .utils.jwt_utils import generate_refresh_token
from .models import (
    LogoutRequest,
    AuthResponse,
    ChangeEmailRequest,
    ChangePasswordRequest,
    ChatMessage,
    ChatMessageRequest,
    EmotionAnalysisResponse,
    Error,
    LoginRequest,
    RegisterRequest,
    RefreshRequest,
    SuccessResponse,
    TestResult,
    TestResultRequest,
    UpdateProfileRequest,
    UserProfile,
    SanProcessRequest,
    SanProcessResponse,
    EmotionalIntelligenceProcessRequest,
    EmotionalIntelligenceProcessResponse,
    PSM25ProcessRequest,
    PSM25ProcessResponse,
    SpielbergerProcessRequest,
    SpielbergerProcessResponse,
    BoykoProcessRequest,
    BoykoProcessResponse,
    MaslachProcessRequest,
    MaslachProcessResponse,
    SelfEsteemProcessRequest,
    SelfEsteemProcessResponse,
    MoodScaleProcessRequest,
    MoodScaleProcessResponse,
)

from .services.ai_service import AIService
from .utils.time_utils import TimeAndSeasonData
import json
import logging
from fastapi.responses import StreamingResponse
from datetime import datetime

from datetime import datetime
from fastapi.middleware.cors import CORSMiddleware

logger = logging.getLogger(__name__)


app = FastAPI(
    title='Эмоции Гид API',
    description='API для веб-версии приложения по отслеживанию эмоционального состояния.\n\n## Общая информация\nAPI предоставляет функциональность для:\n- Аутентификации и управления пользователями\n- Отслеживания эмоционального состояния\n- Чат-бота с искусственным интеллектом\n- Аналитики и визуализации данных\n\n## Аутентификация\nВсе запросы к защищенным эндпоинтам требуют JWT токен в заголовке:\n```\nAuthorization: Bearer <token>\n```\n\n## Форматы данных\nВсе данные передаются в формате JSON.\n\n## Обработка ошибок\nВ случае ошибок API возвращает соответствующий HTTP статус код и объект с описанием ошибки.\n',
    version='1.0.0',
    contact={'email': 'dementjew.vania2016@yandex.ru'},
    servers=[
        {
            'url': 'https://api.emotion-guide.ru/v1',
            'description': 'Основной сервер API',
        }
    ],
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

limiter = Limiter(key_func=get_remote_address)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)


from .services.emotional_intelligence_service import EmotionalIntelligenceService
from .services.psm25_stress_service import PSM25StressService
from .services.spielberger_anxiety_service import SpielbergerAnxietyService
from .services.boyko_burnout_service import BoykoBurnoutService
from .services.maslach_burnout_service import MaslachBurnoutService
from .services.self_esteem_service import SelfEsteemService
from .services.mood_scale_service import MoodScaleService

san_service = SANTestService()
emotional_intelligence_service = EmotionalIntelligenceService()
psm25_service = PSM25StressService()
spielberger_service = SpielbergerAnxietyService()
boyko_service = BoykoBurnoutService()
maslach_service = MaslachBurnoutService()
self_esteem_service = SelfEsteemService()
mood_scale_service = MoodScaleService()
ai_service = AIService()

async def get_current_user_id(authorization: Optional[str] = Header(None)) -> str:
    """Dependency для получения user_id из Firebase токена."""
    if not authorization:
        raise HTTPException(status_code=401, detail="Authorization header missing")
    if not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Invalid authorization header")
    token = authorization.split(" ")[1]
    try:
        decoded = verify_firebase_token(token)
        import logging
        logger = logging.getLogger(__name__)
        logger.info(f"Decoded token uid: {decoded['uid']}")
        return decoded["uid"]
    except Exception as e:
        import logging
        logger = logging.getLogger(__name__)
        logger.error(f"Token verification error: {e}")
        raise HTTPException(status_code=401, detail="Invalid or expired token")


@app.post(
    '/api/auth/refresh',
    response_model=AuthResponse,
    responses={'400': {'model': Error}, '401': {'model': Error}},
    tags=['Аутентификация'],
)
def post_api_auth_refresh(body: RefreshRequest) -> Union[AuthResponse, Error]:
    """
    Обновление access токена по refresh токену
    """
    result = refresh_tokens(body.refreshToken)
    if not result['success']:
        raise HTTPException(status_code=400, detail=result['error'])
    data = result['data']
    # Получить email и username из DB
    user_data = RealtimeDB.get(f'Users/{data["userId"]}')
    return AuthResponse(
        userId=data['userId'],
        email=user_data.get('email') if user_data else None,
        username=user_data.get('username') if user_data else None,
        accessToken=data['accessToken'],
        refreshToken=data['refreshToken']
    )


@app.post(
    '/api/auth/login',
    response_model=AuthResponse,
    responses={'400': {'model': Error}, '401': {'model': Error}},
    tags=['Аутентификация'],
)
def post_api_auth_login(body: LoginRequest) -> Union[AuthResponse, Error]:
    """
    Вход в систему
    """
    result = auth_service.login(body.email, body.password)
    if not result['success']:
        raise HTTPException(status_code=400, detail=result['error'])
    data = result['data']
    # Адаптируем под модель: token = accessToken, добавить refresh
    return AuthResponse(
        userId=data['userId'],
        email=data['email'],
        username=data['username'],
        accessToken=data['accessToken'],
        refreshToken=data['refreshToken']
    )


@app.post(
    '/api/auth/logout',
    response_model=SuccessResponse,
    responses={'400': {'model': Error}, '401': {'model': Error}},
    tags=['Аутентификация'],
)
def post_api_auth_logout(body: LogoutRequest) -> Union[SuccessResponse, Error]:
    """
    Выход из аккаунта с инвалидацией refresh токена
    """
    result = logout_user_tokens(body.refreshToken)
    if not result['success']:
        raise HTTPException(status_code=400, detail=result['error'])
    return SuccessResponse(message=result['message'])


@app.post(
    '/api/auth/register',
    response_model=AuthResponse,
    responses={'400': {'model': Error}, '409': {'model': Error}},
    tags=['Аутентификация'],
)
def post_api_auth_register(body: RegisterRequest) -> Union[AuthResponse, Error]:
    """
    Регистрация нового пользователя
    """
    if not body.termsAccepted:
        raise HTTPException(status_code=400, detail="Terms must be accepted")
    result = auth_service.register(body.email, body.password, body.username, body.termsAccepted)
    if not result['success']:
        raise HTTPException(status_code=409 if "already exists" in result['error'].lower() else 400, detail=result['error'])
    data = result['data']
    return AuthResponse(
        userId=data['userId'],
        email=data['email'],
        username=data['username'],
        accessToken=data['accessToken'],
        refreshToken=generate_refresh_token(data['userId'])
    )


@app.post(
    '/api/chat/analyze-emotions',
    tags=['Чат', 'Аналитика'],
)
async def post_api_chat_analyze_emotions(user_id: str = Depends(get_current_user_id)):
    """
    Анализ результатов теста САН с ИИ.
    """
    from backend.services.SAN_test_service import SANTestService
    san_service = SANTestService()

    # Cooldown check
    metadata = RealtimeDB.get(f'Users/{user_id}/metadata') or {}
    last_analysis = metadata.get('last_analysis_time', 0)
    now = int(datetime.now().timestamp() * 1000)
    if now - last_analysis < 30000:
        raise HTTPException(status_code=429, detail="Cooldown: подождите 30 секунд")

    try:
        time_data_obj = TimeAndSeasonData()
        time_data = time_data_obj.get_time_data()
        results = RealtimeDB.get(f'Users/{user_id}/TestResults') or {}
        sorted_results = sorted(results.values(), key=lambda x: x.get('timestamp', 0), reverse=True)[:25]
        username = RealtimeDB.get(f'Users/{user_id}').get('username', 'Пользователь')

        json_data = san_service.prepare_san_data_for_ai(sorted_results, username, time_data)

        if not sorted_results:
            prompt = ai_service.results_empty_prompt.format(
                username=username,
                season=time_data['season'],
                time_of_day=time_data['timeOfDay'],
                suggestion="прогулку на свежем воздухе" if time_data['timeOfDay'] == "утро" else "чай перед сном"
            )
        else:
            prompt = ai_service.results_not_empty_prompt.format(
                username=username,
                time_of_day=time_data['timeOfDay'],
                season=time_data['season'],
                json_data=json_data
            )

        # Update metadata
        RealtimeDB.update(f'Users/{user_id}/metadata', {'last_analysis_time': now})

        # Get full non-streaming response
        full_ai = ""
        async for chunk in ai_service.send_request(prompt, "", stream=False, max_tokens=2000):
            if chunk:
                full_ai += chunk

        # Save full AI response
        filtered_full = ai_service._filter_response(full_ai)
        ai_data = {
            'content': filtered_full,
            'isUser': False,
            'timestamp': datetime.now().isoformat()
        }
        ai_key = RealtimeDB.create(f'Users/{user_id}/ChatMessages', ai_data)
        
        # Limit to 50 messages
        all_msgs = RealtimeDB.get(f'Users/{user_id}/ChatMessages') or {}
        if len(all_msgs) > 50:
            sorted_keys = sorted(all_msgs.keys(), key=lambda k: all_msgs[k].get('timestamp', ''))[:len(all_msgs)-50]
            for old_key in sorted_keys:
                RealtimeDB.delete(f'Users/{user_id}/ChatMessages/{old_key}')

        return {"success": True, "message": "Анализ завершен"}

    except Exception as e:
        logger.exception("AI emotion analysis failed")
        status_code = 502 if "AI provider" in str(e) else 500
        raise HTTPException(status_code=status_code, detail=str(e))


@app.post(
    '/api/chat/messages',
    tags=['Чат'],
)
async def post_api_chat_messages(body: ChatMessageRequest, user_id: str = Depends(get_current_user_id)):
    """
    Отправка сообщения пользователя в чат и получение AI ответа.
    """
    if not body.isUser:
        raise HTTPException(status_code=400, detail="Only user messages allowed")

    # Cooldown
    metadata = RealtimeDB.get(f'Users/{user_id}/metadata') or {}
    last_chat = metadata.get('last_chat_time', 0)
    now = int(datetime.now().timestamp() * 1000)
    if now - last_chat < 30000:
        raise HTTPException(status_code=429, detail="Cooldown: подождите 30 секунд")

    # Save user message
    user_data = {
        'content': body.content,
        'isUser': True,
        'timestamp': datetime.now().isoformat()
    }
    user_key = RealtimeDB.create(f'Users/{user_id}/ChatMessages', user_data)

    try:
        # History last 10
        all_msgs = RealtimeDB.get(f'Users/{user_id}/ChatMessages') or {}
        sorted_msgs = sorted(all_msgs.values(), key=lambda x: x.get('timestamp', ''), reverse=True)[:10]
        history = [{"role": "user" if m.get('isUser') else "assistant", "content": m.get('content', '')} for m in reversed(sorted_msgs)]

        # Prompt
        prompt = ai_service.system_prompt_chat

        # Update metadata
        RealtimeDB.update(f'Users/{user_id}/metadata', {'last_chat_time': now})

        # Get full non-streaming response
        full_ai = ""
        async for chunk in ai_service.send_request(prompt, body.content, history, stream=False, max_tokens=1500):
            if chunk:
                full_ai += chunk

        # Save full AI response
        filtered_full = ai_service._filter_response(full_ai)
        ai_data = {
            'content': filtered_full,
            'isUser': False,
            'timestamp': datetime.now().isoformat()
        }
        ai_key = RealtimeDB.create(f'Users/{user_id}/ChatMessages', ai_data)
        
        # Limit to 50 messages
        all_msgs = RealtimeDB.get(f'Users/{user_id}/ChatMessages') or {}
        if len(all_msgs) > 50:
            sorted_keys = sorted(all_msgs.keys(), key=lambda k: all_msgs[k].get('timestamp', ''))[:len(all_msgs)-50]
            for old_key in sorted_keys:
                RealtimeDB.delete(f'Users/{user_id}/ChatMessages/{old_key}')

        return {"success": True, "message": "Сообщение отправлено"}

    except Exception as e:
        logger.exception("AI chat message failed")
        status_code = 502 if "AI provider" in str(e) else 500
        raise HTTPException(status_code=status_code, detail=str(e))


@app.get(
    '/api/chat/messages',
    response_model=List[ChatMessage],
    responses={'401': {'model': Error}},
    tags=['Чат'],
)
def get_api_chat_messages(
    limit: Optional[conint(ge=1, le=100)] = 20,
    user_id: str = Depends(get_current_user_id)
) -> Union[List[ChatMessage], Error]:
    """
    Получение истории сообщений
    """
    messages = RealtimeDB.get(f'Users/{user_id}/ChatMessages')
    if not messages:
        return []
    # Сортировка по timestamp (старые сначала), limit последних
    sorted_msgs = sorted(messages.values(), key=lambda x: x.get('timestamp', ''))[-limit:]
    return [ChatMessage(**msg) for msg in sorted_msgs]


@app.get(
    '/api/san/questions',
    response_model=List[dict],
    responses={'401': {'model': Error}},
    tags=['Тесты'],
)
def get_api_san_questions(user_id: str = Depends(get_current_user_id)) -> List[Dict]:
    """
    Получение списка вопросов для теста САН
    """
    return san_service.get_questions()

@app.get(
    '/api/emotional_intelligence/questions',
    response_model=List[dict],
    responses={'401': {'model': Error}},
    tags=['Тесты'],
)
def get_api_emotional_intelligence_questions(user_id: str = Depends(get_current_user_id)) -> List[Dict]:
    """
    Получение списка вопросов для теста на эмоциональный интеллект
    """
    return emotional_intelligence_service.get_questions()

@app.get(
    '/api/psm25_stress/questions',
    response_model=List[dict],
    responses={'401': {'model': Error}},
    tags=['Тесты'],
)
def get_api_psm25_questions(user_id: str = Depends(get_current_user_id)) -> List[Dict]:
    """
    Получение списка вопросов для теста PSM-25 на стресс
    """
    return psm25_service.get_questions()

@app.get(
    '/api/spielberger_anxiety/questions',
    response_model=List[dict],
    responses={'401': {'model': Error}},
    tags=['Тесты'],
)
def get_api_spielberger_questions(user_id: str = Depends(get_current_user_id)) -> List[Dict]:
    """
    Получение списка вопросов для теста Спилберга-Ханина на тревожность
    """
    return spielberger_service.get_questions()

@app.get(
    '/api/boyko_burnout/questions',
    response_model=List[dict],
    responses={'401': {'model': Error}},
    tags=['Тесты'],
)
def get_api_boyko_questions(user_id: str = Depends(get_current_user_id)) -> List[Dict]:
    """
    Получение списка вопросов для теста Бойко на выгорание
    """
    return boyko_service.get_questions()

@app.get(
    '/api/maslach_burnout/questions',
    response_model=List[dict],
    responses={'401': {'model': Error}},
    tags=['Тесты'],
)
def get_api_maslach_questions(user_id: str = Depends(get_current_user_id)) -> List[Dict]:
    """
    Получение списка вопросов для теста Маслач на выгорание
    """
    return maslach_service.get_questions()

@app.get(
    '/api/self_esteem/questions',
    response_model=List[dict],
    responses={'401': {'model': Error}},
    tags=['Тесты'],
)
def get_api_self_esteem_questions(user_id: str = Depends(get_current_user_id)) -> List[Dict]:
    """
    Получение списка вопросов для теста на самооценку
    """
    return self_esteem_service.get_questions()

@app.get(
    '/api/mood_scale/questions',
    response_model=List[dict],
    responses={'401': {'model': Error}},
    tags=['Тесты'],
)
def get_api_mood_scale_questions(user_id: str = Depends(get_current_user_id)) -> List[Dict]:
    """
    Получение списка вопросов для шкалы оценки настроения
    """
    return mood_scale_service.get_questions()


@app.post(
    '/api/san/process',
    response_model=SanProcessResponse,
    responses={'400': {'model': Error}, '401': {'model': Error}},
    tags=['Тесты'],
)
def post_api_san_process(body: SanProcessRequest, user_id: str = Depends(get_current_user_id)) -> Union[SanProcessResponse, Error]:
    """
    Обработка ответов САН и возврат баллов с интерпретацией (сохраняет в DB)
    """
    result = san_service.process_answers(body.answers)
    # Автоматически сохранить
    success = san_service.save_result(user_id, result['wellbeing'], result['activity'], result['mood'])
    if not success:
        raise HTTPException(status_code=500, detail="Failed to save result")
    return SanProcessResponse(
        wellbeing=result['wellbeing'],
        activity=result['activity'],
        mood=result['mood'],
        timestamp=result['timestamp'],
        interpretation=result['interpretation']
    )

@app.post(
    '/api/emotional_intelligence/process',
    response_model=EmotionalIntelligenceProcessResponse,
    responses={'400': {'model': Error}, '401': {'model': Error}},
    tags=['Тесты'],
)
def post_api_emotional_intelligence_process(body: EmotionalIntelligenceProcessRequest, user_id: str = Depends(get_current_user_id)) -> Union[EmotionalIntelligenceProcessResponse, Error]:
    """
    Обработка ответов теста на эмоциональный интеллект
    """
    result = emotional_intelligence_service.process_answers(body.answers)
    success = emotional_intelligence_service.save_result(user_id, result['ei_score'], result['interpretation'])
    if not success:
        raise HTTPException(status_code=500, detail="Failed to save result")
    return EmotionalIntelligenceProcessResponse(
        ei_score=result['ei_score'],
        interpretation=result['interpretation'],
        timestamp=result['timestamp']
    )

@app.post(
    '/api/psm25_stress/process',
    response_model=PSM25ProcessResponse,
    responses={'400': {'model': Error}, '401': {'model': Error}},
    tags=['Тесты'],
)
def post_api_psm25_process(body: PSM25ProcessRequest, user_id: str = Depends(get_current_user_id)) -> Union[PSM25ProcessResponse, Error]:
    """
    Обработка ответов теста PSM-25 на стресс
    """
    result = psm25_service.process_answers(body.answers)
    success = psm25_service.save_result(user_id, result['total_score'], result['interpretation'])
    if not success:
        raise HTTPException(status_code=500, detail="Failed to save result")
    return PSM25ProcessResponse(
        total_score=result['total_score'],
        interpretation=result['interpretation'],
        timestamp=result['timestamp']
    )

@app.post(
    '/api/spielberger_anxiety/process',
    response_model=SpielbergerProcessResponse,
    responses={'400': {'model': Error}, '401': {'model': Error}},
    tags=['Тесты'],
)
def post_api_spielberger_process(body: SpielbergerProcessRequest, user_id: str = Depends(get_current_user_id)) -> Union[SpielbergerProcessResponse, Error]:
    """
    Обработка ответов теста Спилберга-Ханина на тревожность
    """
    result = spielberger_service.process_answers(body.answers)
    success = spielberger_service.save_result(user_id, result['situational_anxiety'], result['personal_anxiety'], result['interpretation'])
    if not success:
        raise HTTPException(status_code=500, detail="Failed to save result")
    return SpielbergerProcessResponse(
        situational_anxiety=result['situational_anxiety'],
        personal_anxiety=result['personal_anxiety'],
        interpretation=result['interpretation'],
        timestamp=result['timestamp']
    )

@app.post(
    '/api/boyko_burnout/process',
    response_model=BoykoProcessResponse,
    responses={'400': {'model': Error}, '401': {'model': Error}},
    tags=['Тесты'],
)
def post_api_boyko_process(body: BoykoProcessRequest, user_id: str = Depends(get_current_user_id)) -> Union[BoykoProcessResponse, Error]:
    """
    Обработка ответов теста Бойко на выгорание
    """
    result = boyko_service.process_answers(body.answers)
    success = boyko_service.save_result(user_id, result['total_score'], result['tension_score'], result['resistance_score'], result['exhaustion_score'], result['interpretation'])
    if not success:
        raise HTTPException(status_code=500, detail="Failed to save result")
    return BoykoProcessResponse(
        total_score=result['total_score'],
        tension_score=result['tension_score'],
        resistance_score=result['resistance_score'],
        exhaustion_score=result['exhaustion_score'],
        interpretation=result['interpretation'],
        timestamp=result['timestamp']
    )

@app.post(
    '/api/maslach_burnout/process',
    response_model=MaslachProcessResponse,
    responses={'400': {'model': Error}, '401': {'model': Error}},
    tags=['Тесты'],
)
def post_api_maslach_process(body: MaslachProcessRequest, user_id: str = Depends(get_current_user_id)) -> Union[MaslachProcessResponse, Error]:
    """
    Обработка ответов теста Маслач на выгорание
    """
    result = maslach_service.process_answers(body.answers)
    success = maslach_service.save_result(user_id, result['exhaustion_score'], result['depersonalization_score'], result['accomplishment_score'], result['interpretation'])
    if not success:
        raise HTTPException(status_code=500, detail="Failed to save result")
    return MaslachProcessResponse(
        exhaustion_score=result['exhaustion_score'],
        depersonalization_score=result['depersonalization_score'],
        accomplishment_score=result['accomplishment_score'],
        interpretation=result['interpretation'],
        timestamp=result['timestamp']
    )

@app.post(
    '/api/self_esteem/process',
    response_model=SelfEsteemProcessResponse,
    responses={'400': {'model': Error}, '401': {'model': Error}},
    tags=['Тесты'],
)
def post_api_self_esteem_process(body: SelfEsteemProcessRequest, user_id: str = Depends(get_current_user_id)) -> Union[SelfEsteemProcessResponse, Error]:
    """
    Обработка ответов теста на самооценку
    """
    result = self_esteem_service.process_answers(body.answers)
    success = self_esteem_service.save_result(user_id, result['self_esteem_score'], result['interpretation'])
    if not success:
        raise HTTPException(status_code=500, detail="Failed to save result")
    return SelfEsteemProcessResponse(
        self_esteem_score=result['self_esteem_score'],
        interpretation=result['interpretation'],
        timestamp=result['timestamp']
    )

@app.post(
    '/api/mood_scale/process',
    response_model=MoodScaleProcessResponse,
    responses={'400': {'model': Error}, '401': {'model': Error}},
    tags=['Тесты'],
)
def post_api_mood_scale_process(body: MoodScaleProcessRequest, user_id: str = Depends(get_current_user_id)) -> Union[MoodScaleProcessResponse, Error]:
    """
    Обработка ответов шкалы оценки настроения
    """
    result = mood_scale_service.process_answers(body.answers)
    success = mood_scale_service.save_result(user_id, result['positive_affect'], result['negative_affect'], result['mood_balance'], result['interpretation'])
    if not success:
        raise HTTPException(status_code=500, detail="Failed to save result")
    return MoodScaleProcessResponse(
        positive_affect=result['positive_affect'],
        negative_affect=result['negative_affect'],
        mood_balance=result['mood_balance'],
        interpretation=result['interpretation'],
        timestamp=result['timestamp']
    )


@app.post(
    '/api/test-results',
    response_model=SuccessResponse,
    responses={'400': {'model': Error}, '401': {'model': Error}},
    tags=['Тесты'],
)
def post_api_test_results(body: TestResultRequest, user_id: str = Depends(get_current_user_id)) -> Union[SuccessResponse, Error]:
    """
    Сохранение готового результата теста САН (альтернатива process)
    """
    # Преобразовать int в float
    wellbeing = float(body.wellbeingScore)
    activity = float(body.activityScore)
    mood = float(body.moodScore)
    success = san_service.save_result(user_id, wellbeing, activity, mood)
    if not success:
        raise HTTPException(status_code=500, detail="Failed to save result")
    return SuccessResponse(message="Test result saved")


@app.get(
    '/api/test-results',
    response_model=List[TestResult],
    responses={'401': {'model': Error}},
    tags=['Тесты'],
)
def get_api_test_results(
    limit: Optional[conint(ge=1, le=50)] = 5,
    user_id: str = Depends(get_current_user_id)
) -> Union[List[TestResult], Error]:
    """
    Получение последних результатов тестов
    """
    results = RealtimeDB.get(f'Users/{user_id}/TestResults')
    if not results:
        return []
    # Сортировка по timestamp, limit последних
    sorted_results = sorted(results.values(), key=lambda x: x.get('timestamp', 0), reverse=True)[:limit]
    test_results = []
    for res in sorted_results:
        test_results.append(TestResult(
            resultId=str(hash(str(res))),  # Pseudo ID
            userId=user_id,
            wellbeingScore=int(res.get('wellbeingScore', 0)),
            activityScore=int(res.get('activityScore', 0)),
            moodScore=int(res.get('moodScore', 0)),
            timestamp=datetime.fromtimestamp(res.get('timestamp', 0) / 1000) if res.get('timestamp') else None
        ))
    return test_results


@app.delete(
    '/api/test-results',
    response_model=SuccessResponse,
    responses={'401': {'model': Error}},
    tags=['Тесты'],
)
def delete_api_test_results(user_id: str = Depends(get_current_user_id)) -> Union[SuccessResponse, Error]:
    """
    Сброс всех результатов тестов
    """
    RealtimeDB.delete(f'Users/{user_id}/TestResults')
    return SuccessResponse(message="All test results deleted")


@app.put(
    '/api/users/change-email',
    response_model=SuccessResponse,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '409': {'model': Error},
    },
    tags=['Пользователи'],
)
def put_api_users_change_email(
    body: ChangeEmailRequest,
    user_id: str = Depends(get_current_user_id)
) -> Union[SuccessResponse, Error]:
    """
    Смена email пользователя
    """
    # Заглушка: Firebase Auth change email требует password verify, но сервис не имеет
    # В реальности: auth.update_user(user_id, email=body.newEmail)
    # Здесь просто update в DB
    RealtimeDB.update(f'Users/{user_id}', {'email': body.newEmail})
    return SuccessResponse(message="Email changed successfully")


@app.post(
    '/api/auth/change-password',
    response_model=SuccessResponse,
    responses={'400': {'model': Error}, '401': {'model': Error}},
    tags=['Аутентификация'],
)
def post_api_auth_change_password(
    body: ChangePasswordRequest,
    user_id: str = Depends(get_current_user_id)
) -> Union[SuccessResponse, Error]:
    """
    Смена пароля пользователя
    """
    result = auth_service.change_password(user_id, body.currentPassword, body.newPassword)
    if not result['success']:
        raise HTTPException(status_code=400, detail=result['error'])
    return SuccessResponse(message=result['message'])


@app.get(
    '/api/users/profile',
    response_model=UserProfile,
    responses={'401': {'model': Error}},
    tags=['Пользователи'],
)
def get_api_users_profile(user_id: str = Depends(get_current_user_id)) -> Union[UserProfile, Error]:
    """
    Получение профиля пользователя
    """
    import logging
    logger = logging.getLogger(__name__)
    profile = RealtimeDB.get(f'Users/{user_id}')
    logger.info(f"DB query for user_id {user_id}: {profile}")
    if not profile:
        raise HTTPException(status_code=404, detail="Profile not found")
    return UserProfile(
        userId=user_id,
        email=profile.get('email'),
        username=profile.get('username'),
        createdAt=datetime.fromisoformat(profile.get('createdAt')) if profile.get('createdAt') else None,
        updatedAt=datetime.now().isoformat()  # Convert to ISO string
    )


@app.put(
    '/api/users/profile',
    response_model=UserProfile,
    responses={'400': {'model': Error}, '401': {'model': Error}},
    tags=['Пользователи'],
)
def put_api_users_profile(body: UpdateProfileRequest, user_id: str = Depends(get_current_user_id)) -> Union[UserProfile, Error]:
    """
    Обновление профиля пользователя
    """
    if body.username:
        RealtimeDB.update(f'Users/{user_id}', {'username': body.username, 'updatedAt': datetime.now().isoformat()})
    # Fetch updated
    profile = RealtimeDB.get(f'Users/{user_id}')
    return UserProfile(
        userId=user_id,
        email=profile.get('email'),
        username=profile.get('username'),
        createdAt=datetime.fromisoformat(profile.get('createdAt')) if profile.get('createdAt') else None,
        updatedAt=datetime.fromisoformat(profile.get('updatedAt')) if profile.get('updatedAt') else None
    )


@app.delete(
    '/api/chat/history',
    response_model=SuccessResponse,
    responses={'401': {'model': Error}},
    tags=['Чат'],
)
def delete_api_chat_history(user_id: str = Depends(get_current_user_id)) -> Union[SuccessResponse, Error]:
    """
    Очистка истории чата.
    """
    RealtimeDB.delete(f'Users/{user_id}/ChatMessages')
    welcome = {
        'content': 'Здравствуйте! Я ваш ИИ-психолог. Расскажите, как дела?',
        'isUser': False,
        'timestamp': datetime.now().isoformat()
    }
    RealtimeDB.create(f'Users/{user_id}/ChatMessages', welcome)
    return SuccessResponse(message="История очищена")


@app.get(
    '/api/chat/metadata',
    response_model=dict,
    responses={'401': {'model': Error}},
    tags=['Чат'],
)
def get_api_chat_metadata(user_id: str = Depends(get_current_user_id)) -> dict:
    """
    Метаданные чата для cooldown.
    """
    metadata = RealtimeDB.get(f'Users/{user_id}/metadata') or {}
    now = int(datetime.now().timestamp() * 1000)
    return {
        "last_chat_time": metadata.get('last_chat_time', 0),
        "chat_cooldown_remaining": max(0, 30000 - (now - metadata.get('last_chat_time', 0))),
        "last_analysis_time": metadata.get('last_analysis_time', 0),
        "analysis_cooldown_remaining": max(0, 30000 - (now - metadata.get('last_analysis_time', 0)))
    }
